import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";

export async function getStaticProps(context) {
  /* Get Posts */
  async function getPosts(params) {
    let config = {
      method: "GET",
      url: `https://jsonplaceholder.typicode.com/posts?_limit=4`,
      header: {
        "Content-Type": "application/json",
      },
    };
    const res = await axios(config);
    return res.data;
  }

  const posts = await getPosts();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <br /> <a href="/">MERN With Next.js!</a>
        </h1>

        <p className={styles.description}>Blog</p>

        <div className={styles.grid}>
          {posts?.length
            ? posts.map((post, index) => (
                <a href="/" key={index} className={styles.card}>
                  <h2>{post.title} &rarr;</h2>
                  <p>{post.body}</p>
                </a>
              ))
            : ""}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>@2022</p>
      </footer>
    </div>
  );
}
